title: IBM API Connect Test and Monitor
email: test@atm.ibm.com
description: IBM API Connect Test and Monitor
keywords: IBM, docker, container, devops, applications, development, iteration, microservices, cloud, ICP, services, rapid, integrated
baseurl: "/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude: [node_modules]
collections:
  documentations:
    output: true
  news:
    output: true
